### PR TITLE
Add a way to install development tools on fedora and arch linux to readme.

### LINKED ISSUE #2: Building on Fedora
On Fedora 35, I was able to build like this.

With the compiler arm-none-eabi-gcc.

```
$ sudo dnf install arm-none-eabi-gcc-cs libftdi-devel

$ which arm-none-eabi-gcc
/bin/arm-none-eabi-gcc

$ make BOARD=hx20 CROSS_COMPILE=arm-none-eabi-
```

With the compiler arm-linux-gnu-gcc.

```
$ sudo dnf install gcc-arm-linux-gnu libftdi-devel

$ which arm-linux-gnu-gcc
/bin/arm-linux-gnu-gcc

$ make BOARD=hx20 CROSS_COMPILE=arm-linux-gnu-
```

If you don't mind, I would like to add the steps using `arm-none-eabi-gcc` on `README.md`.

### PR DESCRIPTION
**Pull request by junaruga**
This PR fixes #2 by adding the way to install development tools on Fedora. I tested it on Fedora Linux 35. You can check the modified readme [here](https://github.com/junaruga/EmbeddedController/blob/wip/readme-fedora-build/README.md).

### CODE REVIEW

**Comment by Foxboron** [comment]
If you wouldn't mind, you can add the following section as well:


<pre>
On Arch Linux

```
sudo pacman -S arm-none-eabi-gcc libftdi
```

<pre>

**Comment by junaruga** [comment]
@Foxboron Sure. I rebased this PR, adding the command for Arch Linux. Does the `libftdi` is development package including the header files? On Fedora, the `libftdi-devel` RPM package includes the header files (`*.h`) and requires `libftdi` that only includes shard object library files (`*.so`).

**Comment by Foxboron** [comment]
@junaruga In Arch Linux we don't split packages. So `libftdi` contains documentation, headers, so-names and so on.

Check the file listing here: https://archlinux.org/packages/community/x86_64/libftdi/

**Comment by junaruga** [comment]
@Foxboron OK. Thanks!

By the way, rebased this PR again adding the links to the Linux distributions. The format of [this podman installation guide](https://podman.io/getting-started/installation.html#linux-distributions) inspired me.

**Comment by junaruga** [comment]
> By the way, rebased this PR again adding the links to the Linux distributions. The format of this podman installation guide inspired me.

Rebased without links again , keeping only essential parts to be merged easily. :)

**Review by kiram9 — APPROVED** [review]

**Pull request merged**
